# 数据源配置
spring.datasource.platform=mysql

db.num=1
db.url.0=jdbc:mysql://mysql:3306/ry-config?characterEncoding=utf8&connectTimeout=10000&socketTimeout=30000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
db.user=root
db.password=mysql1234

# 服务地址配置（必要时配置）
server.servlet.contextPath=/nacos
server.port=8848

# 权限认证配置
nacos.core.auth.system.type=nacos
nacos.core.auth.enabled=true
nacos.core.auth.plugin.nacos.token.secret.key=Gnj4Fp4OP9WJQie60IK2h8LL+wKXRM0PrhGcuW9uHhc=
nacos.core.auth.server.identity.key=nacos
nacos.core.auth.server.identity.value=nacos

# 日志目录（可选）
server.tomcat.basedir=/home/nacos

# 启用兼容模式避免高版本 bug（v3.0+建议）
nacos.naming.empty-service.auto-clean=true